# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eccd88038b037aa8012306d39be8de88786eb79a776f21746c857ade941b42a0ef333e647e338b14e82e63094de6ec78c8ccf51f49dca6ef44e3382f74a89a22

test:
  secret_key_base: 0fd48e8b0317bbf33389d9585a85bfac7ff08b5ce58ef4bcfc597ce379b74e9cda1f0dd025e4076b9eb175717f18ecce1a0d7e56ccd8530845d377651307aead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
